### ISSUE TITLE
Ability to launch an eclair web application to visualize data in the browser

### ISSUE THREAD

**Issue by yan-zaretskiy** [mindv0rtex/eclair#14]

**Comment by yan-zaretskiy** [comment]
Roughly, I would like to have a web-based UI looking smth like this:
<img width="1303" alt="Screen Shot 2020-05-04 at 21 22 59" src="https://user-images.githubusercontent.com/10409817/81027932-826c8f00-8e4d-11ea-8ff7-b2655572ae05.png">

We can use Plotly.js for plotting. The next question is whether to have a separate back-end or not. I think that since `eclair` is intended to be run locally we can shove everything into the browser. I would love to try using Rust compiled to WASM and use as little JS as I can get away with.

**Comment by ErichDonGubler** [comment]
Hey, I see this is still assigned to me. What support were you hoping for from here? :)

**Comment by yan-zaretskiy** [comment]
I'll take it from here, thank you! :)
